name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn
      - name: Build and add to release draft
        run: yarn ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
